### ISSUE TITLE
Níveis no grupo

### ISSUE THREAD

**Issue by luisascastro13** [luisascastro13/agora#18]
IF > IFRS > IFRS Canoas > Grêmio Estudantil > DS4

O ADM do nível de cima pode adicionar ADMs ao nível debaixo. Mais alguma outra função?

**Comment by rafaelcp** [comment]
Remover dos níveis abaixo?

**Comment by luisascastro13** [comment]
Resolvi cancelar essa ideia de encadeamento porque não existe na prática e por enquanto só complica o meu pensamento.
