### ISSUE TITLE
Visibilidade do evento

### ISSUE THREAD

**Issue by luisascastro13** [luisascastro13/agora#19]
Os membros do grupo podem ver qual usuário criou/convidou para um evento ou aparecerá somente o nome do grupo?
Por exemplo:

Assembleia, dia 08/09/2020 - Grêmio Estudantil (publicado por Luísa de Castro)

**Comment by rafaelcp** [comment]
Me parece que mostrar a pessoa é uma boa. Até para os outros admins saberem quem enviou.

**Comment by luisascastro13** [comment]
Os "núcleos" ou grupos serão como páginas no Facebook. Um usuário poderá seguir a página e será incluído na lista de presença da mesma, caso haja assembleia. Os moderadores do núcleo serão os únicos capazes de criar assembleias e documentos (ata, lista de presença, votação) nas mesmas.

A visibilidade do nome de quem fez a criação de tal assembleia ou documento ficará visível somente para os próprios moderadores.
